CREATE TABLE `hremployees` (
	`employeeid` INT(11) NOT NULL AUTO_INCREMENT,
	`employeenumber` VARCHAR(20) NOT NULL,
	`userid` VARCHAR(20) DEFAULT NULL,
	`addressbookid` INT(11) DEFAULT NULL,
	`firstname` VARCHAR(50) NOT NULL,
	`middlename` VARCHAR(50) DEFAULT NULL,
	`lastname` VARCHAR(50) NOT NULL,
	`hiredate` DATE NOT NULL,
	`terminationdate` DATE DEFAULT NULL,
	`birthdate` DATE DEFAULT NULL,
	`gender` ENUM('M','F','Other') DEFAULT NULL,
	`email` VARCHAR(100) DEFAULT NULL,
	`phone` VARCHAR(20) DEFAULT NULL,
	`departmentid` INT(11) DEFAULT NULL,
	`positionid` INT(11) DEFAULT NULL,
	`supervisorid` INT(11) DEFAULT NULL,
	`employmentstatus` ENUM('Active','Terminated','On Leave','Suspended') DEFAULT 'Active',
	`employmenttype` ENUM('Full-Time','Part-Time','Contract','Temporary') DEFAULT NULL,
	`locationid` INT(11) DEFAULT NULL,
	`currentsalary` DECIMAL(15,2) DEFAULT NULL,
	`createddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`modifieddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`createdby` VARCHAR(50) DEFAULT NULL,
	`modifiedby` VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (`employeeid`),
	UNIQUE KEY `employeenumber` (`employeenumber`),
	UNIQUE KEY `userid` (`userid`),
	KEY `idx_supervisor` (`supervisorid`),
	KEY `idx_department` (`departmentid`),
	KEY `idx_position` (`positionid`),
	KEY `idx_status` (`employmentstatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
